server:
  host: 0.0.0.0
  port: 8080
  contextPath: /shortener

management:
  host: 0.0.0.0
  port: 8080
  contextPath: /manage

  application.name: shortener

default:
  suffix.length: 8
  domain: http://crazylabz.io/

geo:
  token: e0984224e81098a055d6b993c962ea98
  